"""
Streamlit app for the Enteric Methane AI project.

The app allows a user to:
    - enter a ruminant diet and animal profile
    - generate an ML-based enteric methane prediction
    - compare the prediction with an empirical/IPCC-style benchmark equation
    - inspect global model drivers
    - view mitigation-opportunity outputs from the explainability pipeline
    - optionally display saved PubMed evidence briefs generated by rag_pubmed.py

Run:
    streamlit run app/app.py

Required previous steps:
    python src/generate_synthetic_data.py
    python src/data_prep.py
    python src/train_models.py
    python src/explain.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List

import joblib
import pandas as pd
import streamlit as st


# ---------------------------------------------------------------------
# Import project modules
# ---------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = BASE_DIR / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from benchmark_equation import predict_ch4_g_kg_dmi  # noqa: E402
from model_inputs import build_input_row  # noqa: E402


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

MODEL_PATH = BASE_DIR / "models" / "best_model.joblib"
FEATURE_IMPORTANCE_PATH = BASE_DIR / "outputs" / "explainability" / "feature_importance.csv"
MITIGATION_OPPORTUNITY_PATH = BASE_DIR / "outputs" / "explainability" / "mitigation_opportunities.csv"
RAG_OUTPUT_DIR = BASE_DIR / "outputs" / "rag"


# ---------------------------------------------------------------------
# Streamlit configuration
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="Enteric Methane AI Assistant",
    page_icon="🐄",
    layout="wide",
)

st.title("🐄 Enteric Methane Prediction & Evidence Assistant")

st.caption(
    "Research and portfolio prototype for sustainable ruminant nutrition. "
    "This is not a validated on-farm decision system."
)


# ---------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------

@st.cache_resource
def load_model_bundle(path: Path) -> Dict[str, object]:
    """
    Load trained model bundle.
    """

    return joblib.load(path)


def load_csv_if_exists(path: Path) -> pd.DataFrame | None:
    """
    Read small output files fresh on each rerun.

    Do not cache a missing-file result: a later deployment may add the CSV
    at the same path while the Streamlit process is still running.
    """

    if not path.exists():
        return None

    return pd.read_csv(path)


def display_input_checks(inputs: Dict[str, float | int | str]) -> None:
    """
    Display simple responsible-use checks for unusual user inputs.
    """

    warnings = []

    if float(inputs["forage_pct"]) < 10 or float(inputs["forage_pct"]) > 90:
        warnings.append(
            "Forage percentage is near the edge of the expected range. "
            "The prediction may be less reliable."
        )

    if float(inputs["starch_g_kg"]) > 450:
        warnings.append(
            "Starch level is very high. Interpret methane prediction together "
            "with rumen health and diet formulation constraints."
        )

    if float(inputs["ee_g_kg"]) > 70:
        warnings.append(
            "Dietary fat/ether extract is high. Practical use should consider "
            "intake, digestibility, and animal performance."
        )

    if str(inputs["additive_type"]) != "none" and float(inputs["additive_dose"]) == 0:
        warnings.append(
            "An additive type was selected, but additive dose is 0. "
            "The additive effect may not be represented meaningfully."
        )

    if str(inputs["additive_type"]) == "none" and float(inputs["additive_dose"]) > 0:
        warnings.append(
            "Additive dose is greater than 0 while additive type is 'none'. "
            "The app will still predict, but the input is inconsistent."
        )

    for warning in warnings:
        st.warning(warning)


def show_feature_importance() -> None:
    """
    Show saved global feature importance with its method label.
    """

    importance_df = load_csv_if_exists(FEATURE_IMPORTANCE_PATH)

    if importance_df is None:
        st.info(
            "Feature-importance output was not found. Run "
            "`python src/explain.py` to populate this section."
        )
        return

    top_n = importance_df.head(10).copy()

    st.subheader("Global model drivers: top 10")
    st.caption(
        "These are global drivers of the trained model, not a causal explanation "
        "for one specific farm or ration."
    )
    if "method" in importance_df.columns:
        st.caption("Method: " + "; ".join(importance_df["method"].dropna().unique()))

    st.bar_chart(top_n.set_index("feature")["importance"])

    with st.expander("Show feature-importance table"):
        display_cols = [
            col
            for col in [
                "rank",
                "feature",
                "importance",
                "relative_importance_pct",
                "method",
            ]
            if col in top_n.columns
        ]
        st.dataframe(importance_df[display_cols], width="stretch")


def show_mitigation_opportunities() -> None:
    """
    Show model-based mitigation sensitivity scenarios from explain.py.
    """

    opportunity_df = load_csv_if_exists(MITIGATION_OPPORTUNITY_PATH)

    if opportunity_df is None:
        st.info(
            "Mitigation-opportunity output was not found. Run "
            "`python src/explain.py` to populate this section."
        )
        return

    st.subheader("Model-based mitigation-opportunity sensitivity table")
    st.caption(
        "Negative delta values indicate that the trained model predicts lower "
        "methane yield under that controlled scenario. This is model sensitivity "
        "analysis, not validated ration advice."
    )
    if "reference_kind" in opportunity_df.columns:
        st.info(
            "Precomputed demonstration using 27 synthetic profiles, not real farms "
            "or original training rows. These results do not change with the prediction form. "
            "The scenarios are model-input probes, not fully balanced rations. "
            "Rank is a sorting order, not proven mitigation efficacy."
        )
        st.caption(
            "Delta = scenario mean minus baseline mean, in g CH₄/kg DMI. "
            "Normalized additive dose 1 is not a physical feeding dose and is not "
            "biologically comparable across additives."
        )

    display_cols = [
        col
        for col in [
            "rank",
            "scenario",
            "estimated_delta_g_ch4_kg_dmi",
            "baseline_mean_prediction",
            "intervention_mean_prediction",
            "interpretation",
        ]
        if col in opportunity_df.columns
    ]

    st.dataframe(opportunity_df[display_cols], width="stretch")


def show_rag_briefs() -> None:
    """
    Display saved, source-linked PubMed literature briefs.
    """

    st.subheader("Saved PubMed evidence briefs")

    if not RAG_OUTPUT_DIR.exists():
        st.info(
            "No RAG output folder found yet. Generate an evidence brief from the "
            "command line, for example: "
            '`python src/rag_pubmed.py --topic "3-NOP methane dairy cattle"`'
        )
        return

    brief_files = sorted(RAG_OUTPUT_DIR.glob("evidence_brief_*.md"))

    if not brief_files:
        st.info(
            "No evidence brief files found yet. Generate one with "
            '`python src/rag_pubmed.py --topic "3-NOP methane dairy cattle"`.'
        )
        return

    selected_file = st.selectbox(
        "Select saved evidence brief",
        brief_files,
        format_func=lambda path: path.read_text(encoding="utf-8").splitlines()[0].lstrip("# "),
    )

    st.markdown(selected_file.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------

if not MODEL_PATH.exists():
    st.error(
        "No trained model found. Run the project pipeline first:\n\n"
        "`python src/generate_synthetic_data.py`\n\n"
        "`python src/data_prep.py`\n\n"
        "`python src/train_models.py`\n\n"
        "`python src/explain.py`"
    )
    st.stop()

bundle = load_model_bundle(MODEL_PATH)
model = bundle["model"]
feature_cols = bundle["feature_cols"]
model_name = bundle.get("model_name", type(model).__name__)

with st.sidebar:
    st.header("Project status")
    st.success("Trained model loaded")
    st.write(f"**Model:** {model_name}")
    st.write(f"**Features:** {len(feature_cols)}")

    st.divider()

    st.caption(
        "Use this app to demonstrate the workflow. Scientific or commercial "
        "decisions require full validation with real data and expert review."
    )

tab_predict, tab_explain, tab_evidence, tab_about = st.tabs(
    [
        "Prediction",
        "Explainability",
        "Evidence briefs",
        "About",
    ]
)

with tab_predict:
    st.header("1. Diet and animal profile")

    col1, col2, col3 = st.columns(3)

    with col1:
        dmi_kg = st.number_input(
            "Dry matter intake (kg/day)",
            min_value=3.0,
            max_value=35.0,
            value=20.0,
            step=0.5,
        )
        cp_g_kg = st.number_input(
            "Crude protein (g/kg DM)",
            min_value=20.0,
            max_value=350.0,
            value=160.0,
            step=1.0,
        )
        ndf_g_kg = st.number_input(
            "NDF (g/kg DM)",
            min_value=50.0,
            max_value=850.0,
            value=400.0,
            step=1.0,
        )
        adf_g_kg = st.number_input(
            "ADF (g/kg DM)",
            min_value=20.0,
            max_value=600.0,
            value=220.0,
            step=1.0,
        )

    with col2:
        ee_g_kg = st.number_input(
            "Ether extract / fat (g/kg DM)",
            min_value=0.0,
            max_value=120.0,
            value=35.0,
            step=1.0,
        )
        starch_g_kg = st.number_input(
            "Starch (g/kg DM)",
            min_value=0.0,
            max_value=550.0,
            value=220.0,
            step=5.0,
        )
        forage_pct = st.slider(
            "Forage proportion (% of diet DM)",
            min_value=0,
            max_value=100,
            value=55,
            step=1,
        )
        st.metric("Concentrate proportion", f"{100 - forage_pct:.0f}%")

    with col3:
        body_weight_kg = st.number_input(
            "Body weight (kg)",
            min_value=250.0,
            max_value=900.0,
            value=575.0,
            step=5.0,
        )
        milk_yield_kg = st.number_input(
            "Milk yield (kg/day)",
            min_value=0.0,
            max_value=70.0,
            value=28.0,
            step=1.0,
        )
        lactating = st.selectbox(
            "Lactation status",
            options=[1, 0],
            format_func=lambda value: "Lactating" if value == 1 else "Non-lactating / dry",
        )
        breed = st.selectbox(
            "Breed",
            options=["Holstein", "Jersey", "Crossbred", "Other"],
        )

    st.subheader("Feed additive")
    col4, col5 = st.columns(2)

    with col4:
        additive_type = st.selectbox(
            "Additive type",
            options=[
                "none",
                "3-NOP",
                "seaweed",
                "tannin",
                "nitrate",
                "lipid",
                "other",
            ],
        )

    with col5:
        additive_dose = st.number_input(
            "Additive dose (normalized units)",
            min_value=0.0,
            max_value=3.0,
            value=0.0,
            step=0.1,
        )

    inputs = {
        "dmi_kg": dmi_kg,
        "cp_g_kg": cp_g_kg,
        "ndf_g_kg": ndf_g_kg,
        "adf_g_kg": adf_g_kg,
        "ee_g_kg": ee_g_kg,
        "starch_g_kg": starch_g_kg,
        "forage_pct": forage_pct,
        "body_weight_kg": body_weight_kg,
        "milk_yield_kg": milk_yield_kg,
        "lactating": lactating,
        "breed": breed,
        "additive_type": additive_type,
        "additive_dose": additive_dose,
    }

    display_input_checks(inputs)

    if st.button("Predict methane output", type="primary"):
        X_input = build_input_row(feature_cols, inputs)

        pred_ml = float(model.predict(X_input)[0])
        pred_benchmark = float(
            predict_ch4_g_kg_dmi(
                pd.Series([dmi_kg]),
                pd.Series([forage_pct]),
            ).iloc[0]
        )

        total_ch4_ml = pred_ml * dmi_kg
        total_ch4_benchmark = pred_benchmark * dmi_kg
        difference = pred_ml - pred_benchmark

        st.header("2. Prediction results")

        metric_col1, metric_col2, metric_col3 = st.columns(3)

        metric_col1.metric(
            "ML prediction",
            f"{pred_ml:.1f} g CH₄/kg DMI",
        )
        metric_col2.metric(
            "Empirical benchmark",
            f"{pred_benchmark:.1f} g CH₄/kg DMI",
            delta=f"{difference:+.1f} vs ML",
            delta_color="inverse",
        )
        metric_col3.metric(
            "Estimated total CH₄",
            f"{total_ch4_ml:.0f} g/day",
        )

        with st.expander("Show prediction details"):
            prediction_details = pd.DataFrame(
                {
                    "metric": [
                        "ML methane yield",
                        "Benchmark methane yield",
                        "ML total methane",
                        "Benchmark total methane",
                        "Difference: ML - benchmark",
                    ],
                    "value": [
                        f"{pred_ml:.2f} g CH4/kg DMI",
                        f"{pred_benchmark:.2f} g CH4/kg DMI",
                        f"{total_ch4_ml:.1f} g/day",
                        f"{total_ch4_benchmark:.1f} g/day",
                        f"{difference:+.2f} g CH4/kg DMI",
                    ],
                }
            )
            st.dataframe(prediction_details, use_container_width=True)

        st.info(
            "Interpretation: the ML prediction is based on the trained dataset "
            "and learned feature relationships. The benchmark is a transparent "
            "empirical comparator. Differences between them are useful for model "
            "discussion, not automatic proof that one is biologically correct."
        )

with tab_explain:
    st.header("Explainability and mitigation sensitivity")
    show_feature_importance()
    st.divider()
    show_mitigation_opportunities()

with tab_evidence:
    st.header("Scientific literature snapshots")
    st.caption(
        "Three curated briefs, based on six selected PubMed-indexed studies. "
        "Sources checked on 4 September 2026. These are saved snapshots, not a live "
        "search, systematic review, or validation of the model's predictions."
    )
    show_rag_briefs()

with tab_about:
    st.header("About this prototype")

    st.markdown(
        """
        This app is part of the **enteric-methane-ai** portfolio project.

        The project demonstrates how animal nutrition domain expertise can be
        combined with:

        - regression modelling
        - empirical benchmark comparison
        - explainable AI
        - model-based mitigation sensitivity analysis
        - PubMed evidence retrieval

        ### Responsible-use statement

        This tool is a research and portfolio prototype. It should not be used
        as a validated on-farm decision system. Methane mitigation decisions
        require real experimental data, full scientific review, animal
        performance evaluation, economic assessment, and qualified expert input.
        """
    )
