"""
Clean and feature-engineer the enteric methane dataset.

This script works with either:
    1. The synthetic placeholder dataset produced by generate_synthetic_data.py
    2. A real external methane mitigation dataset placed in data/raw/

Input:
    data/raw/synthetic_mitigation_dataset.csv

Output:
    data/processed/clean_dataset.csv
    data/processed/data_quality_report.txt

The cleaning pipeline:
    - loads CSV or Excel input
    - keeps the core diet, animal, additive, and methane variables
    - validates required columns
    - coerces numeric columns safely
    - reports missing values
    - imputes missing numeric predictors using the median
    - fills missing categorical values as "unknown"
    - applies basic physiological sanity filters
    - engineers concentrate_pct
    - one-hot encodes categorical features for modelling
"""

from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

# For the portfolio/demo pipeline, this file is generated by:
# python src/generate_synthetic_data.py
RAW_PATH = RAW_DIR / "synthetic_mitigation_dataset.csv"

CLEAN_DATA_PATH = PROCESSED_DIR / "clean_dataset.csv"
QUALITY_REPORT_PATH = PROCESSED_DIR / "data_quality_report.txt"


# ---------------------------------------------------------------------
# Column configuration
# ---------------------------------------------------------------------

TARGET_COL = "ch4_g_kg_dmi"

ID_COLS = ["study_id"]

NUMERIC_PREDICTOR_COLS = [
    "dmi_kg",
    "cp_g_kg",
    "ndf_g_kg",
    "adf_g_kg",
    "ee_g_kg",
    "starch_g_kg",
    "forage_pct",
    "body_weight_kg",
    "milk_yield_kg",
    "lactating",
    "additive_dose",
]

TARGET_COLS = [
    "ch4_g_kg_dmi",
    "ch4_g_day",
]

CATEGORICAL_COLS = [
    "breed",
    "additive_type",
]

REQUIRED_COLS = [
    "dmi_kg",
    "ndf_g_kg",
    "forage_pct",
    "ch4_g_kg_dmi",
]

# Conservative sanity ranges.
# These are not strict biological laws. They are used to remove obvious
# placeholder/data-entry errors before model training.
SANITY_RANGES: Dict[str, Tuple[float, float]] = {
    "dmi_kg": (3, 35),
    "cp_g_kg": (20, 350),
    "ndf_g_kg": (50, 850),
    "adf_g_kg": (20, 600),
    "ee_g_kg": (0, 120),
    "starch_g_kg": (0, 550),
    "forage_pct": (0, 100),
    "body_weight_kg": (250, 900),
    "milk_yield_kg": (0, 70),
    "additive_dose": (0, 20),
    "ch4_g_kg_dmi": (5, 45),
    "ch4_g_day": (20, 1000),
}


# ---------------------------------------------------------------------
# Loading and validation
# ---------------------------------------------------------------------

def load_raw(path: Path = RAW_PATH) -> pd.DataFrame:
    """
    Load raw data from CSV or Excel.

    Parameters
    ----------
    path:
        Path to raw data file.

    Returns
    -------
    pandas.DataFrame
        Raw dataset.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"No data found at: {path}\n"
            "Run `python src/generate_synthetic_data.py` first, or place the "
            "real external dataset in data/raw/ and update RAW_PATH."
        )

    if path.suffix.lower() in [".xlsx", ".xls"]:
        return pd.read_excel(path)

    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)

    raise ValueError(
        f"Unsupported file type: {path.suffix}. Use .csv, .xlsx, or .xls."
    )


def validate_required_columns(df: pd.DataFrame) -> None:
    """
    Check that the minimum required columns are present.
    """

    missing_required = [col for col in REQUIRED_COLS if col not in df.columns]

    if missing_required:
        raise ValueError(
            "The dataset is missing required columns: "
            f"{missing_required}. Available columns: {list(df.columns)}"
        )


def select_relevant_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Keep only columns used by the current modelling pipeline.

    Real external datasets may contain many more variables. This project keeps
    a focused subset so that the modelling pipeline remains transparent and
    reproducible.
    """

    configured_cols = (
        ID_COLS
        + NUMERIC_PREDICTOR_COLS
        + TARGET_COLS
        + CATEGORICAL_COLS
    )

    keep_cols = [col for col in configured_cols if col in df.columns]
    return df[keep_cols].copy()


# ---------------------------------------------------------------------
# Cleaning helpers
# ---------------------------------------------------------------------

def coerce_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert configured numeric columns to numeric dtype.

    Invalid parsing values are converted to NaN and handled later.
    """

    df = df.copy()
    numeric_cols = [
        col
        for col in NUMERIC_PREDICTOR_COLS + TARGET_COLS
        if col in df.columns
    ]

    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def apply_sanity_filters(df: pd.DataFrame) -> Tuple[pd.DataFrame, List[str]]:
    """
    Remove rows outside conservative physiological sanity ranges.

    Returns
    -------
    cleaned_df:
        Dataset after sanity filtering.
    filter_log:
        Human-readable summary of how many rows were removed by each filter.
    """

    df = df.copy()
    filter_log = []

    for col, (lower, upper) in SANITY_RANGES.items():
        if col not in df.columns:
            continue

        before = len(df)
        df = df[df[col].between(lower, upper) | df[col].isna()]
        removed = before - len(df)

        if removed > 0:
            filter_log.append(
                f"{col}: removed {removed} rows outside [{lower}, {upper}]"
            )

    return df, filter_log


def impute_numeric_predictors(df: pd.DataFrame) -> pd.DataFrame:
    """
    Median-impute missing numeric predictors and create missingness indicators.

    Target columns are not imputed.
    """

    df = df.copy()

    for col in NUMERIC_PREDICTOR_COLS:
        if col not in df.columns:
            continue

        was_missing = df[col].isna()

        if was_missing.any():
            df[f"{col}_was_missing"] = was_missing.astype(int)
            median_value = df[col].median()
            df[col] = df[col].fillna(median_value)

    return df


def clean_categorical_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Fill missing categorical values and standardize text formatting.
    """

    df = df.copy()

    for col in CATEGORICAL_COLS:
        if col not in df.columns:
            continue

        df[col] = (
            df[col]
            .astype("string")
            .fillna("unknown")
            .str.strip()
            .replace("", "unknown")
        )

    return df


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create additional interpretable nutrition features.
    """

    df = df.copy()

    if "forage_pct" in df.columns:
        df["concentrate_pct"] = 100 - df["forage_pct"]

    if "ch4_g_day" not in df.columns and {"ch4_g_kg_dmi", "dmi_kg"}.issubset(df.columns):
        df["ch4_g_day"] = df["ch4_g_kg_dmi"] * df["dmi_kg"]

    if "milk_yield_kg" in df.columns and "dmi_kg" in df.columns:
        df["milk_per_kg_dmi"] = np.where(
            df["dmi_kg"] > 0,
            df["milk_yield_kg"] / df["dmi_kg"],
            np.nan,
        )

    return df


def encode_categoricals(df: pd.DataFrame) -> pd.DataFrame:
    """
    One-hot encode categorical columns for machine learning models.
    """

    categorical_cols_present = [
        col for col in CATEGORICAL_COLS if col in df.columns
    ]

    if not categorical_cols_present:
        return df

    return pd.get_dummies(
        df,
        columns=categorical_cols_present,
        drop_first=False,
        dtype=int,
    )


# ---------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------

def build_quality_report(
    raw_df: pd.DataFrame,
    cleaned_before_encoding: pd.DataFrame,
    final_df: pd.DataFrame,
    filter_log: List[str],
) -> str:
    """
    Build a plain-text data quality report.
    """

    raw_missing = raw_df.isna().sum()
    raw_missing = raw_missing[raw_missing > 0].sort_values(ascending=False)

    report_lines = [
        "Enteric Methane AI - Data Quality Report",
        "=" * 48,
        "",
        "Input summary",
        "-------------",
        f"Raw rows: {len(raw_df)}",
        f"Raw columns: {raw_df.shape[1]}",
        "",
        "Missing values in raw data",
        "--------------------------",
    ]

    if raw_missing.empty:
        report_lines.append("No missing values detected.")
    else:
        for col, count in raw_missing.items():
            pct = (count / len(raw_df)) * 100
            report_lines.append(f"{col}: {count} missing ({pct:.1f}%)")

    report_lines.extend(
        [
            "",
            "Sanity filtering",
            "----------------",
        ]
    )

    if filter_log:
        report_lines.extend(filter_log)
    else:
        report_lines.append("No rows removed by sanity filters.")

    report_lines.extend(
        [
            "",
            "Output summary",
            "--------------",
            f"Rows after cleaning before encoding: {len(cleaned_before_encoding)}",
            f"Final rows: {len(final_df)}",
            f"Final columns: {final_df.shape[1]}",
            "",
            "Final columns",
            "-------------",
        ]
    )

    report_lines.extend(list(final_df.columns))

    return "\n".join(report_lines)


# ---------------------------------------------------------------------
# Main cleaning pipeline
# ---------------------------------------------------------------------

def clean(df: pd.DataFrame) -> Tuple[pd.DataFrame, str]:
    """
    Clean and feature-engineer raw methane data.

    Returns
    -------
    final_df:
        Cleaned and encoded dataset ready for model training.
    quality_report:
        Plain-text summary of data quality and cleaning decisions.
    """

    raw_df = df.copy()

    validate_required_columns(raw_df)

    df = select_relevant_columns(raw_df)
    df = coerce_numeric_columns(df)

    # Drop rows without the main target.
    before_drop_target = len(df)
    df = df.dropna(subset=[TARGET_COL])
    dropped_target = before_drop_target - len(df)

    df, filter_log = apply_sanity_filters(df)

    if dropped_target > 0:
        filter_log.insert(
            0,
            f"{TARGET_COL}: removed {dropped_target} rows with missing target",
        )

    df = clean_categorical_columns(df)
    df = impute_numeric_predictors(df)
    df = engineer_features(df)

    cleaned_before_encoding = df.copy()
    final_df = encode_categoricals(df)
    final_df = final_df.reset_index(drop=True)

    quality_report = build_quality_report(
        raw_df=raw_df,
        cleaned_before_encoding=cleaned_before_encoding,
        final_df=final_df,
        filter_log=filter_log,
    )

    return final_df, quality_report


def main() -> None:
    """
    Run the full data preparation pipeline.
    """

    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    raw_df = load_raw()
    print(f"Loaded {len(raw_df)} raw records from: {RAW_PATH}")

    clean_df, quality_report = clean(raw_df)

    clean_df.to_csv(CLEAN_DATA_PATH, index=False)
    QUALITY_REPORT_PATH.write_text(quality_report, encoding="utf-8")

    print(
        f"Wrote {len(clean_df)} cleaned records "
        f"({clean_df.shape[1]} columns) to: {CLEAN_DATA_PATH}"
    )
    print(f"Wrote data quality report to: {QUALITY_REPORT_PATH}")


if __name__ == "__main__":
    main()
